name       : fstrcmp
version    : 0.7
release    : 2
source     :
    - http://fstrcmp.sourceforge.net/fstrcmp-0.7.D001.tar.gz : e4018e850f80700acee8da296e56e15b1eef711ab15157e542e7d7e1237c3476
license    : GPL-2.0-or-later
component  : programming.library
summary    : Library used to make fuzzy comparisons of strings and byte arrays.
description: |
    The fstrcmp project provides a library that is used to make fuzzy comparisons of strings and byte arrays, including multi-byte character strings. This can be useful in error messages, enabling the suggestion of likely valid alternatives. In compilers, this can reduce the cascade of secondary errors.
builddeps  :
    - ghostscript
    - groff
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
